Repository DuckDuckStudio/Sundry, pull requests merged in 2025-06, with the labels that each got.

#14 feat(modify): 给用户看到底清单哪里出了问题
  src/tools/modify.py
Labels: DEV-开发分支合并, DEV-测试通过, 优化

#20 docs: 文档大改
  .github/ISSUE_TEMPLATE/bug_feedback.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/preference_adjective.yml
  README.md
  docs/photos/README/Demo/Commands/cat.png
  docs/photos/README/Demo/Commands/config.png
  docs/photos/README/Demo/Commands/fun.png
  docs/photos/README/Demo/Commands/help.png
  docs/photos/README/Demo/Commands/ignore.png
  docs/photos/README/Demo/Commands/modify.png
  docs/photos/README/Demo/Commands/remove.png
  docs/photos/README/Demo/Commands/repr.png
  docs/photos/README/Demo/Commands/revert.png
  docs/photos/README/Demo/Commands/sync.png
  docs/photos/README/Demo/Commands/ver.png
  src/tools/maintain/config.py
  src/tools/modify.py
Labels: DEV-开发分支合并, DEV-测试通过, 文档

#22 feat: Azure Pipline 日志分析: sundry logs-analyse <Azure Pipline Url> [是否保留日志文件] [是否显示一般错误/异常]
  README.md
  docs/photos/README/Demo/Commands/logs-analyse.png
  src/sundry.py
  src/tools/logsAnalyse.py
Labels: DEV-开发分支合并, DEV-测试通过

#24 不指定具体分支，添加 test.yaml
  .github/workflows/test.yaml
Labels: DEV-测试通过, github_actions

#23 ci: 测试工作流
  .github/workflows/build.yaml
  .github/workflows/test.yaml
  .gitignore
Labels: DEV-开发分支合并, DEV-测试通过, 新功能, github_actions

#25 docs: 徽章
  README.md
Labels: DEV-测试通过, 文档
